export async function getWikiImageLink(requestTitle) {
  // https://en.wikipedia.org/w/api.php?action=query&prop=pageimages&format=json&piprop=original&titles=India
  const data = await fetch(`https://en.wikipedia.org/w/api.php?action=query&prop=pageimages&format=json&piprop=original&titles=${requestTitle}&redirects=1`);
  const response = await data.json(); 
  const pages = response.query.pages; 
  if (pages.hasOwnProperty(-1)) {
    return "";
  }
  else {
    return pages[Object.keys(pages)[0]].original.source;
  }
}

export function getNames() {

  const birdNames = [
    "Cassin's finch",
    'Limpkin',
    'Roadside hawk',
    'Blue jay',
    "Steller's jay",
    'Grey crowned crane',
    'Scarlet flycatcher',
    'American avocet',
    'Kori bustard',
    'Yellow-billed magpie',
    'Canada jay',
    'Sandhill crane',
    'Northern waterthrush',
    'Ardea herodias occidentalis',
    'Sora (bird)',
    'Mexican duck',
    'Grey wagtail',
    'Pacific-slope flycatcher',
    'Least flycatcher',
    'Buff-breasted flycatcher',
    'Willow flycatcher',
    "Hammond's flycatcher",
    'Cordilleran flycatcher',
    'Virginia rail',
    'Common crane',
    'Boat-tailed grackle',
    'Barnacle goose',
    'Yucatan jay',
    'Inca jay',
    "Wilson's storm petrel",
    'Greater Antillean grackle',
    'Brown jay',
    'Boat-billed flycatcher',
    'Dusky moorhen',
    'Chicken',
    'Helmeted guineafowl',
    'Junco hyemalis caniceps',
    "Cassin's kingbird",
    'Eastern kingbird',
    'Scissor-tailed flycatcher',
    'Thick-billed kingbird',
    'Western kingbird',
    'Fork-tailed flycatcher',
    'Weka',
    'White-throated magpie-jay',
    'Black-throated magpie-jay',
    'American coot',
    'Rose-throated becard',
    'Rough-legged buzzard',
    'Black swan',
    'North Island saddleback',
    'Great black-backed gull',
    'Great kiskadee',
    'American black duck',
    'New Zealand pipit',
    'Eastern phoebe',
    'Black phoebe',
    'Masked tityra',
    'Lineated woodpecker',
    'Australasian swamphen',
    'White-cheeked pintail',
    'White-faced heron',
    'Green-winged teal',
    'Chukar partridge',
    'Least grebe',
    "Bell's sparrow",
    'Red junglefowl',
    'Pyrrhuloxia',
    'Northern cardinal',
    "Lincoln's sparrow",
    'Pied-billed grebe',
    'Swamp sparrow',
    'Wild turkey',
    'Ocellated turkey',
    'Willow ptarmigan',
    'Black-chinned sparrow',
    'Alpine chough',
    "Brewer's sparrow",
    'Mountain bluebird',
    'Field sparrow',
    'Pacific black duck',
    'Fox sparrow',
    'American flamingo',
    'Eurasian blackcap',
    "Bell's vireo",
    'Plumbeous vireo',
    'Philadelphia vireo',
    'Yellow-throated vireo',
    'Red-eyed vireo',
    "Harris's sparrow",
    "Hutton's vireo",
    'White-throated sparrow',
    'Golden-crowned sparrow',
    'Yellowhammer',
    "Barrow's goldeneye",
    'Common reed bunting',
    'Warbling vireo',
    'European serin',
    'Yellow-fronted canary',
    'Kalij pheasant',
    'Elegant euphonia',
    'Yellow-throated euphonia',
    'Scrub euphonia',
    'Tricolored blackbird',
    "Lesson's motmot",
    'Warbling white-eye',
    'Pelagic cormorant',
    'Hooded oriole',
    "Audubon's oriole",
    'African pied wagtail',
    'Anas superciliosa × platyrhynchos',
    'Streak-backed oriole',
    'Altamira oriole',
    'Common linnet',
    'Grey-cheeked thrush',
    'White-breasted waterhen',
    'Indian peafowl',
    'Clapper rail',
    'Kākā',
    'Green-tailed towhee',
    'Spotted towhee',
    'Eastern towhee',
    'Domestic Muscovy duck',
    'Australian pied cormorant',
    'American three-toed woodpecker',
    "Nuttall's woodpecker",
    'Ladder-backed woodpecker',
    "Gambel's quail",
    'Eurasian bullfinch',
    'Neotropic cormorant',
    'Downy woodpecker',
    'Northern bobwhite',
    'Cinnamon-rumped seedeater',
    'Hairy woodpecker',
    'Semipalmated sandpiper',
    'Black-backed woodpecker',
    'Greater scaup',
    'Red-billed tropicbird',
    'Eastern meadowlark',
    'Budgerigar',
    'Lesser scaup',
    'New Zealand scaup',
    'Montezuma quail',
    'Brown pelican',
    'White-throated dipper',
    "Ross's goose",
    'California quail',
    'Common grackle',
    'Great-tailed grackle',
    'Scaled quail',
    'Pileated woodpecker',
    'Blue grosbeak',
    'Berylline hummingbird',
    'Common yellowthroat',
    'Black-headed trogon',
    'Common whitethroat',
    'Pine grosbeak',
    'Evening grosbeak',
    'Hawfinch',
    'Golden-winged warbler',
    'Hoatzin',
    'Setophaga coronata coronata',
    'Cinnamon-bellied flowerpiercer',
    'Bluish-grey saltator',
    'Black-headed saltator',
    'Saffron finch',
    'Mandarin duck',
    'Junco hyemalis hyemalis',
    'Orange-fronted parakeet',
    'Little pied cormorant',
    'Summer tanager',
    'Scarlet tanager',
    'Hepatic tanager',
    'Black-throated sparrow',
    'Kelp gull',
    'Squirrel cuckoo',
    'Rufous-crowned sparrow',
    "Lewis's woodpecker",
    'Gila woodpecker',
    'Savannah sparrow',
    'Black-cheeked woodpecker',
    'Rock wren',
    'Red-bellied woodpecker',
    'Golden-cheeked woodpecker',
    'Acorn woodpecker',
    'Northern flicker',
    'Rufous-capped warbler',
    'Yellow-legged gull',
    'Scarlet-rumped tanager',
    'Burrowing owl',
    'Cackling goose',
    'Brambling',
    'Common chaffinch',
    'Dark-eyed junco',
    'Common cuckoo',
    'Yellow-eyed junco',
    "Nelson's sparrow",
    'Grasshopper sparrow',
    'Seaside sparrow',
    'Black-billed cuckoo',
    'Mangrove cuckoo',
    'Yellow-billed cuckoo',
    "Clark's nutcracker",
    'Groove-billed ani',
    'Vesper sparrow',
    'Olive sparrow',
    'Greater roadrunner',
    'Lesser roadrunner',
    'Bananaquit',
    'Painted bunting',
    'Australian brushturkey',
    'Orange-breasted bunting',
    'Lazuli bunting',
    'Yellow-breasted chat',
    'Great curassow',
    'Crested guan',
    'White-rumped shama',
    'Yellow-billed cardinal',
    'Red-legged honeycreeper',
    'Microcarbo melanoleucos brevirostris',
    "Williamson's sapsucker",
    'Rose-breasted grosbeak',
    'Red-breasted sapsucker',
    'Black-headed grosbeak',
    'Red-naped sapsucker',
    'West Mexican chachalaca',
    'Plain chachalaca',
    'Pied crow',
    'Black-and-white warbler',
    'Blue-black grassquit',
    'Palm tanager',
    'Russet-crowned motmot',
    "Brewer's blackbird",
    'Sulphur-crested cockatoo',
    'Junco hyemalis oreganus',
    'Pacific golden plover',
    'Bronzed cowbird',
    'Brown-headed cowbird',
    'Little bee-eater',
    'European bee-eater',
    'Collared aracari',
    'Red crossbill',
    'Asian green bee-eater',
    'Two-barred crossbill',
    'European roller',
    'Lilac-breasted roller',
    'Indian roller',
    'Yellow-headed blackbird',
    'Lark sparrow',
    'Bobolink',
    'Osprey',
    'Phainopepla',
    "Couch's kingbird",
    'Common chiffchaff',
    'Circus cyaneus hudsonius',
    'Magpie-lark',
    'Snow bunting',
    'Lark bunting',
    'Ruby-crowned kinglet',
    'Common firecrest',
    'Goldcrest',
    'Golden-crowned kinglet',
    'Tropical kingbird',
    'Australian pelican',
    'Emerald toucanet',
    'Sacred kingfisher',
    "Bullock's oriole",
    'Dickcissel',
    'Gray kingbird',
    'Black tern',
    'Striped sparrow',
    'Montezuma oropendola',
    'Fieldfare',
    'Stitchbird',
    'Secretarybird',
    'Rose-ringed parakeet',
    'Eastern rosella',
    'Prothonotary warbler',
    'Ringed kingfisher',
    'Kākā',
    'Red-crowned amazon',
    'White-fronted amazon',
    'Yellow-headed amazon',
    'Whinchat',
    'Military macaw',
    'American tree sparrow',
    'Pied kingfisher',
    'American pygmy kingfisher',
    'Amazon kingfisher',
    'Social flycatcher',
    'Curve-billed thrasher',
    'Belted kingfisher',
    'Horned lark',
    'Australian king parrot',
    'Olive-backed sunbird',
    'Ivory-billed woodcreeper',
    'Wattled jacana',
    'Red phalarope',
    'European turtle dove',
    'Black-billed magpie',
    'Hooded crow',
    'Monk parakeet',
    'Eurasian collared dove',
    'Western tanager',
    'Least bittern',
    'Verdin',
    "MacGillivray's warbler",
    'Rock dove',
    'Hooded warbler',
    'Cerulean warbler',
    'Common wood pigeon',
    'Flame-colored tanager',
    'White-crowned pigeon',
    'Band-tailed pigeon',
    'Red-billed pigeon',
    'Prairie warbler',
    'Common nighthawk',
    'Lesser nighthawk',
    'Eurasian spoonbill',
    'Common poorwill',
    'House finch',
    'Purple finch',
    'Pauraque',
    'Pale-billed woodpecker',
    'Brown thrasher',
    'White-tipped dove',
    'Northern potoo',
    'Eurasian wigeon',
    'Gray hawk',
    'Calliope hummingbird',
    'Western screech owl',
    'Grey-headed swamphen',
    'Eastern screech owl',
    'Eared dove',
    'Blue duck',
    'Black-throated blue warbler',
    'Northern beardless tyrannulet',
    'Crested caracara',
    'Common ground dove',
    'Olive-throated parakeet',
    'Kea',
    'Ruddy ground dove',
    'Zebra dove',
    'Little owl',
    'Smooth-billed ani',
    'Eastern bluebird',
    'African spoonbill',
    'Great horned owl',
    'Cave swallow',
    'Purple martin',
    'Setophaga coronata auduboni',
    'Welcome swallow',
    'Barn swallow',
    'Surfbird',
    'Ruff (bird)',
    'Royal spoonbill',
    'Violet-green swallow',
    'Hadada ibis',
    'Sand martin',
    'American white ibis',
    'Glossy ibis',
    'White-faced ibis',
    'Common raven',
    'Northern rough-winged swallow',
    'Masked booby',
    'Red-footed booby',
    'Brown booby',
    'Australasian gannet',
    'Little penguin',
    'Yellow-eyed penguin',
    'Hamerkop',
    'Eurasian wren',
    'Red knot',
    'Red-backed shrike',
    "Baird's sandpiper",
    'Wild turkey',
    'Western sandpiper',
    'Purple sandpiper',
    'Dunlin',
    'Curlew sandpiper',
    'Pectoral sandpiper',
    'Short-billed dowitcher',
    'Superb fairywren',
    'Common greenshank',
    'Todiramphus sanctus vagans',
    'Green sandpiper',
    'Wood sandpiper',
    'Greater yellowlegs',
    'Lesser yellowlegs',
    'Eurasian curlew',
    'Eurasian whimbrel',
    'Phalacrocorax carbo novaehollandiae',
    'Petroica macrocephala macrocephala',
    'Petroica australis longipes',
    'Tūī',
    'Short-eared owl',
    'New Zealand fantail',
    'American woodcock',
    'Ruddy turnstone',
    'Black turnstone',
    'Rhipidura fuliginosa placabilis',
    'Black-tailed godwit',
    'Hudsonian godwit',
    'Marbled godwit',
    'Red-necked phalarope',
    'Upland sandpiper',
    'Bar-tailed godwit',
    'Northern saw-whet owl',
    'Common sandpiper',
    'Coconut lorikeet',
    'Northern hawk-owl',
    'Blue-gray gnatcatcher',
    'Chipping sparrow',
    'Red-whiskered bulbul',
    'Indigo bunting',
    'Varied bunting',
    'Noisy miner',
    'Crested pigeon',
    'Jabiru',
    'Red-vented bulbul',
    'Swan goose',
    'European green woodpecker',
    'Black-footed albatross',
    'Common ostrich',
    'Laysan albatross',
    'Northern fulmar',
    'Grey francolin',
    'Broad-billed hummingbird',
    'Black-necked grebe',
    'Great crested grebe',
    'Horned grebe',
    'Great spotted woodpecker',
    'Red-necked grebe',
    'Little grebe',
    'Mountain plover',
    'Double-crested cormorant',
    'Great cormorant',
    "Brandt's cormorant",
    "Clark's grebe",
    'Great white pelican',
    'American white pelican',
    'Mourning dove',
    'Masked lapwing',
    'Western gull',
    'Slaty-tailed trogon',
    "Thayer's gull",
    "Heermann's gull",
    'Yellow-footed gull',
    'Common gull',
    'Iceland gull',
    'Ring-billed gull',
    'Collared trogon',
    'White-winged dove',
    'Lesser black-backed gull',
    'California gull',
    'Tūī',
    'Elegant trogon',
    'Glaucous-winged gull',
    'Citreoline trogon',
    'Pigeon guillemot',
    'Pied stilt',
    'Black guillemot',
    'New Zealand bellbird',
    'Marabou stork',
    'Australian white ibis',
    'Blue-gray tanager',
    'White-tailed hawk',
    'Arctic tern',
    'Common tern',
    "Forster's tern",
    'Great grey shrike',
    'Resplendent quetzal',
    'White-fronted tern',
    'Parasitic jaeger',
    'Pomarine jaeger',
    'Grey teal',
    'Black-legged kittiwake',
    'Black skimmer',
    'Razorbill',
    'Atlantic puffin',
    'Tufted puffin',
    'Common blackbird',
    'Red-legged thrush',
    'Clay-colored thrush',
    'American robin',
    'Mistle thrush',
    'Rhinoceros auklet',
    'Song thrush',
    'Rufous-tailed jacamar',
    'Northern jacana',
    'European stonechat',
    'Eurasian hoopoe',
    'Rusty blackbird',
    'Pacific loon',
    'Tropical mockingbird',
    'Italian sparrow',
    'Common loon',
    'Red-throated loon',
    'Northern wheatear',
    'Magnificent frigatebird',
    'Great frigatebird',
    'Eurasian hobby',
    'Prairie falcon',
    'Aplomado falcon',
    'Peregrine falcon',
    'Bat falcon',
    'American kestrel',
    'Barred owl',
    'Merlin (bird)',
    'Common moorhen',
    "Wilson's warbler",
    "Swainson's thrush",
    'New Zealand falcon',
    'Hermit thrush',
    'Veery',
    'Crested caracara',
    'Laughing falcon',
    'Lapland longspur',
    'Yellow-headed caracara',
    'White stork',
    'Wood stork',
    'Yellow-billed stork',
    'Western bluebird',
    'Saddle-billed stork',
    'Turkey vulture',
    "Townsend's solitaire",
    'Lesser yellow-headed vulture',
    'King vulture',
    'Black vulture',
    'Great grey owl',
    'African openbill',
    'Grey plover',
    'California condor',
    'Spotted flycatcher',
    'Killdeer',
    "Wilson's plover",
    'Piping plover',
    'Common redstart',
    'Black redstart',
    'Little ringed plover',
    'Turquoise-browed motmot',
    'Garganey',
    'Black-necked stilt',
    'Black oystercatcher',
    'Eurasian magpie',
    'Eurasian oystercatcher',
    'Variable oystercatcher',
    'Northern lapwing',
    'Spur-winged lapwing',
    'Blacksmith lapwing',
    'Bluethroat',
    'Inca dove',
    'Pied avocet',
    'Common pheasant',
    'American golden plover',
    'American dipper',
    'European robin',
    'Golden-fronted woodpecker',
    'Common ringed plover',
    'Western reef heron',
    'Little blue heron',
    'Tricolored heron',
    'Snowy egret',
    'Little egret',
    'Pacific reef heron',
    'Blue rock thrush',
    'Cocoi heron',
    'Grey heron',
    'Great blue heron',
    'Black-crowned night heron',
    'Rufous-backed thrush',
    'Squacco heron',
    'Yellow-crowned night heron',
    'Grey-cowled wood rail',
    'Western cattle egret',
    'Green heron',
    'American purple gallinule',
    'American bittern',
    'Boat-billed heron',
    'Australasian darter',
    'African darter',
    'Canyon towhee',
    'Golden eagle',
    'Wood thrush',
    'Mexican jay',
    'Sharp-shinned hawk',
    'Eurasian sparrowhawk',
    'Northern goshawk',
    'Reddish egret',
    'Common goldeneye',
    'Brown noddy',
    'Spotted sandpiper',
    'Purple heron',
    'Collared kingfisher',
    'Whooping crane',
    'Black-winged stilt',
    'Mountain pygmy owl',
    'Swamp harrier',
    'Western marsh harrier',
    'Little black cormorant',
    'Zone-tailed hawk',
    'Striated heron',
    'Roseate spoonbill',
    'Short-tailed hawk',
    'Great egret',
    "Swainson's hawk",
    'Red-legged partridge',
    'Red-shouldered hawk',
    'Red-tailed hawk',
    'Snowy plover',
    'Wandering tattler',
    'Willet',
    'Bateleur',
    "Wilson's snipe",
    'Common black hawk',
    "Bonaparte's gull",
    'Short-toed snake eagle',
    'Silver gull',
    'Black-headed gull',
    'Laughing gull',
    "Franklin's gull",
    'Sooty tern',
    'Least tern',
    'Caspian tern',
    'Royal tern',
    'Greater crested tern',
    'White-tailed kite',
    'Egyptian goose',
    'Laughing dove',
    'Grey warbler',
    'Bald eagle',
    'Grass wren',
    'African fish eagle',
    'Snowy owl',
    'Mottled owl',
    'Ruffed grouse',
    'Black-collared hawk',
    'Snail kite',
    'Red kite',
    'Eurasian griffon vulture',
    'European pied flycatcher',
    'Blue-capped motmot',
    'Semipalmated plover',
    'Brahminy kite',
    'White-backed vulture',
    'Mississippi kite',
    'Melodious blackbird',
    'Black-crested titmouse',
    'Tufted titmouse',
    'Oak titmouse',
    'Song sparrow',
    'Eurasian siskin',
    'White wagtail',
    'Brown creeper',
    'Southern ground hornbill',
    'Meadow pipit',
    'Buff-bellied pipit',
    'Mangrove swallow',
    'Carolina chickadee',
    'Black-capped chickadee',
    'Mountain chickadee',
    'Chestnut-backed chickadee',
    'Coal tit',
    'Green honeycreeper',
    'Common waxbill',
    'Eurasian blue tit',
    'Yellow-bellied sapsucker',
    'Cliff swallow',
    'Pacific wren',
    'Winter wren',
    'Eurasian tree sparrow',
    'House sparrow',
    'California scrub jay',
    'Buff-bellied hummingbird',
    'Rufous-tailed hummingbird',
    'Fork-tailed drongo',
    'Violet-crowned hummingbird',
    'Scaly-breasted munia',
    'Bare-throated tiger heron',
    'Porphyrio melanotus melanotus',
    'Black scoter',
    'Clay-colored sparrow',
    'Cinnamon hummingbird',
    'Zenaida dove',
    'Dunnock',
    'Common kestrel',
    'Varied thrush',
    'Ruby-throated hummingbird',
    'Blue-throated mountaingem',
    'Dusky-capped flycatcher',
    'American redstart',
    'Brown-crested flycatcher',
    'Silvereye',
    'White-crowned sparrow',
    'Red-winged blackbird',
    'Great tit',
    'Rufous-collared sparrow',
    'Tennessee warbler',
    'Orange-crowned warbler',
    'Nashville warbler',
    'Mourning warbler',
    'Kentucky warbler',
    'Cape May warbler',
    'Northern parula',
    'Magnolia warbler',
    'Bay-breasted warbler',
    'Blackburnian warbler',
    'American yellow warbler',
    'Blackpoll warbler',
    'Palm warbler',
    'Pine warbler',
    'Yellow-rumped warbler',
    'Yellow-throated warbler',
    'Violet sabrewing',
    "Cassin's vireo",
    'Black-throated gray warbler',
    "Townsend's warbler",
    'Hermit warbler',
    'Golden-cheeked warbler',
    'Black-throated green warbler',
    'Canada warbler',
    'Red warbler',
    'Florida scrub jay',
    'Red-headed woodpecker',
    'Corn bunting',
    'Common redpoll',
    'Pine siskin',
    'Yellow-winged tanager',
    'Lesser goldfinch',
    "Lawrence's goldfinch",
    'American goldfinch',
    'African sacred ibis',
    'White tern',
    'Tree swallow',
    'Kelp gull',
    'Java sparrow',
    'American oystercatcher',
    'European greenfinch',
    "Cooper's hawk",
    'Blue-headed vireo',
    'Broad-tailed hummingbird',
    'Red-billed gull',
    'Western grebe',
    'Kererū',
    "Sabine's gull",
    'Keel-billed toucan',
    'Laughing kookaburra',
    'Eurasian coot',
    'Hirundo rustica erythrogaster',
    "Costa's hummingbird",
    "Anna's hummingbird",
    'Northern flicker',
    'Blue-footed booby',
    'Oriental magpie-robin',
    "Allen's hummingbird",
    'Rufous hummingbird',
    'Lucifer sheartail',
    'Common bulbul',
    'Larus glaucescens × occidentalis',
    "Woodhouse's scrub jay",
    'White-necked jacobin',
    'South Island oystercatcher',
    'Spruce grouse',
    'Black-chinned hummingbird',
    'Hen harrier',
    'Eastern great egret',
    'Great crested flycatcher',
    'Ferruginous hawk',
    'White-throated swift',
    "Vaux's swift",
    'Chimney swift',
    'Chestnut-sided warbler',
    'Loggerhead shrike',
    'Anhinga',
    'Common myna',
    'Pygmy nuthatch',
    'African jacana',
    'Red-breasted nuthatch',
    'Eurasian nuthatch',
    'Brown-headed nuthatch',
    'Common swift',
    'Common starling',
    'Ovenbird',
    'Western yellow wagtail',
    'White-eyed vireo',
    'Long-billed thrasher',
    'Sanderling',
    'California thrasher',
    'Common gallinule',
    'Stilt sandpiper',
    "Rivoli's hummingbird",
    'Black-vented oriole',
    "Scott's oriole",
    'Broad-winged hawk',
    'Common snipe',
    'Orchard oriole',
    'Least sandpiper',
    'Gray catbird',
    'Takahē',
    'White-rumped sandpiper',
    "Wilson's phalarope",
    'Colaptes auratus auratus',
    'Blue mockingbird',
    'Yellow-faced grassquit',
    'Sage thrasher',
    'Long-billed dowitcher',
    'Solitary sandpiper',
    'White-breasted nuthatch',
    'Common redshank',
    'Black-bellied whistling duck',
    'White-faced whistling duck',
    'Fulvous whistling duck',
    'Black-backed oriole',
    'Southern lapwing',
    'Trumpeter swan',
    'Whooper swan',
    'Tundra swan',
    'Mute swan',
    'Baltimore oriole',
    'Mallard',
    'Northern pintail',
    'Eurasian teal',
    'Cinnamon teal',
    'Mottled duck',
    'Blue-winged teal',
    'Gadwall',
    'Northern shoveler',
    'Brown teal',
    'Willie wagtail',
    'American wigeon',
    'Bufflehead',
    'Red-breasted merganser',
    'Common merganser',
    'Greylag goose',
    'Greater white-fronted goose',
    'Common eider',
    "Ridgway's rail",
    'Crimson rosella',
    'Velvet scoter',
    'Black kite',
    'Gull-billed tern',
    'Morepork',
    'Surf scoter',
    'Ring-necked duck',
    'Common pochard',
    'Tufted duck',
    'Long-billed curlew',
    'Snow goose',
    'Wrentit',
    'Canada goose',
    'Elegant tern',
    'Nene (bird)',
    'Redhead (bird)',
    'Wood duck',
    'Hooded merganser',
    'Harlequin duck',
    'Nanday parakeet',
    'Green parakeet',
    'Muscovy duck',
    'Red-crested pochard',
    'Red-masked parakeet',
    "Say's phoebe",
    'Canvasback',
    'White-headed woodpecker',
    'Blue-winged warbler',
    'American crow',
    'Long-eared owl',
    'American crow',
    'Long-tailed duck',
    'Australian wood duck',
    'Sandwich tern',
    'Galah',
    'Golden-olive woodpecker',
    'Wild turkey',
    'Grey silky-flycatcher',
    'Swallow-tailed kite',
    'European goldfinch',
    'Mexican cacique',
    'Sooty grouse',
    'American bushtit',
    'Long-tailed tit',
    'Silvereye',
    'White-bellied sea eagle',
    'Common murre',
    'Tringa semipalmata inornatus',
    'Eurasian skylark',
    'Crested lark',
    'Common house martin',
    'Worm-eating warbler',
    'White-eared hummingbird',
    'Northern mockingbird',
    'Australian magpie',
    'Common kingfisher',
    'Spotted dove',
    'Cedar waxwing',
    'Bohemian waxwing',
    'Common shelduck',
    'South Island robin',
    'Red-lored amazon',
    'Dusky grouse',
    'Canyon wren',
    'Ruddy shelduck',
    'Cactus wren',
    'Veracruz wren',
    'New Zealand fantail',
    'Black-tailed gnatcatcher',
    'Brown pelican',
    "Abert's towhee",
    'California towhee',
    'Carolina wren',
    "Harris's hawk",
    'Domestic duck',
    'House wren',
    'Buteo lineatus elegans',
    'Barred antshrike',
    "Bewick's wren",
    'Paradise shelduck',
    'Slate-throated whitestart',
    'Australian pied cormorant',
    'Painted redstart',
    'American herring gull',
    'Louisiana waterthrush',
    'Nazca booby',
    'Scarlet macaw',
    'Stripe-headed sparrow',
    'Buff-breasted sandpiper',
    'Greater flamingo',
    'Northern gannet',
    'Brown pelican',
    'Ferruginous pygmy owl',
    'Ruddy duck',
    'Ash-throated flycatcher',
    'Green kingfisher',
    'Western meadowlark',
    'Yellow-throated toucan',
    'Red-crested cardinal',
    'Common buzzard',
    'Sulphur-bellied flycatcher',
    'Western wood pewee',
    'Carrion crow',
    'Red-crowned parakeet',
    'Eastern wood pewee',
    'Greater pewee',
    'Olive-sided flycatcher',
    'European herring gull',
    'White-throated kingfisher',
    'Red-winged starling',
    'Blue bunting',
    'Marsh wren',
    'Barn owl',
    'Gartered trogon',
    'Western jackdaw',
    'Fish crow',
    'African penguin',
    'Rook (bird)',
    'House crow',
    'Brant (goose)',
    'Glaucous gull',
    'Domestic pigeon',
    'Eurasian jay',
    'Greylag goose',
    'Northern tufted flycatcher',
    'Pink-footed shearwater',
    'Great shearwater'
  ]; 

  return birdNames; 
}